# Generated by Django 3.1.7 on 2021-03-23 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancyapp', '0002_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacancyList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(max_length=30)),
                ('url', models.URLField()),
            ],
        ),
    ]
