# Generated by Django 3.1.7 on 2021-03-23 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancyapp', '0003_vacancylist'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrappedData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('company', models.CharField(max_length=60)),
                ('status', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('link', models.URLField()),
            ],
        ),
    ]
