# Generated by Django 3.1.7 on 2021-03-27 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancyapp', '0004_scrappeddata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrappeddata',
            name='company',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='scrappeddata',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scrappeddata',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scrappeddata',
            name='location',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='scrappeddata',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='scrappeddata',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
