# Generated by Django 3.1.7 on 2021-03-30 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancyapp', '0005_auto_20210327_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrappeddata',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
