# Generated by Django 3.1.7 on 2021-04-05 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancyapp', '0007_scrappeddata_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrappedAdvert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('company', models.CharField(blank=True, max_length=60, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('posted_date', models.CharField(blank=True, max_length=20, null=True)),
                ('scrapped_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScrappedTender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('company', models.CharField(blank=True, max_length=60, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('close_date', models.CharField(blank=True, max_length=20, null=True)),
                ('scrapped_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScrappedVacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('company', models.CharField(blank=True, max_length=60, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('location', models.CharField(blank=True, max_length=30, null=True)),
                ('due_date', models.CharField(blank=True, max_length=30, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
