# Generated by Django 3.1.7 on 2021-04-05 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancyapp', '0008_scrappedadvert_scrappedtender_scrappedvacancy'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrappedtender',
            name='posted_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
