# Generated by Django 3.1.7 on 2021-04-05 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancyapp', '0009_scrappedtender_posted_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrappedtender',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
