# Generated by Django 3.2 on 2021-04-08 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancyapp', '0010_auto_20210405_1941'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrappedNew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=30, null=True)),
                ('site', models.CharField(blank=True, max_length=60, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image_link', models.URLField(blank=True, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('posted_date', models.CharField(blank=True, max_length=20, null=True)),
                ('scrapped_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
